name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USER }}/bada:latest
          ${{ secrets.DOCKER_USER }}/bada:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/bada:cache
        cache-to: type=inline

    - name: Security Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USER }}/bada:latest

    - name: Image digest
      run: echo "Image digest is ${{ steps.docker_build.outputs.digest }}"
